---
title: "Try barchart"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Data bearbejdning

```{r}
# import + processing of data
# and process

library(readxl)
library(tidyverse)

# columns named according to DST. 
# use fill from tidyr to fill enhed column. 
# --> fills values top-down until it encounters next valid value

df <- read_xlsx("~/Desktop/Data Visualization/Uden navn/data/all_data.xlsx", skip = 2) %>% 
  rename(enhed=`...1`,varegruppe=`...2`) %>% 
  fill(enhed, .direction="down")

# convert all except first to columns to numeric 

df[, 3:ncol(df)] <- df[, 3:ncol(df)] %>% 
  mutate_if(is.character, as.numeric)
  
# check that was before ".." is now NA (i.e., no inconsistencies in formatting)

temp <- read_xlsx("~/Desktop/Data Visualization/Uden navn/data/all_data.xlsx", skip = 2) %>% 
  rename(enhed=`...1`,varegruppe=`...2`) %>% 
  fill(enhed, .direction="down")

sum(temp == "..") == sum(is.na(df))

##### Note: Jeg har ikke fjernet NA rækker, men det burde man nok 

# have to convert month variables to "month" variable in order to plot data
# big data frame

df <- df %>% pivot_longer(cols=`2020M01`:`2022M08`,names_to = "maaned",values_to="vaerdi")

# instead of having three rows for one group with values (indeks, ...), 
# have one column per group with respective values
# split code and description afterwards
# rename columns

df <- df %>% 
  group_by(enhed) %>%
  pivot_wider(names_from = enhed, values_from = vaerdi) %>% 
  separate(varegruppe, into=c("kode","beskrivelse"),sep="\\s",extra="merge") %>% 
  rename(vaerdi_i = Indeks, vaerdi_ae_m = `Ændring i forhold til måneden før (pct.)`, vaerdi_ae_aa = `Ændring i forhold til samme måned året før (pct.)`)

# create code levels

df <- df %>% 
  mutate(niv_1 = ifelse(str_count(kode,"\\.")==0,kode,NA), 
         niv_2=ifelse(str_count(kode,"\\.")==1,kode,NA), 
         niv_3=ifelse(str_count(kode,"\\.")==2,kode,NA),
         niv_4=ifelse(str_count(kode,"\\.")==3,kode,NA))


df <- df %>%
  mutate(Dato = str_replace(maaned, "M", "-")) %>%
  mutate(Dato = paste0(as.character(Dato), "-01")) %>% 
  mutate(Dato = as.Date(Dato, format = "%Y-%m-%d"))
```




```{r}
#Pakker til visualisering
library(ggplot2)
library(plotly)
```


```{r}
'''
                              selectInput("y_var",
                                          label = "Enhed:",
                                          choices = c("Indeks", "Sidste måned", "Samme måned sidste år"),
                                          selected =  "Sidste måned"),
                              selectInput("order_input",
                                          label = "Sortering:",
                                          choices = c("Numerisk", "Aftagende", "Stigende"),
                                          selected =  "Numerisk",),
                              selectInput("niveau_in",
                                          label = "Niveau:",
                                          choices = c("Nievau 1", "Niveau 2", "Niveau 3", "Niveau 4"),
                                          selected =  "Nievau 1"),
                              airDatepickerInput("year_month_input",
                                                 label = "Month of interest:",
                                                 value = max(df$Date),
                                                 minDate = min(df$Date),
                                                 maxDate = max(df$Date),
                                                 view = "months",
                                                 minView = "months", 
                                                 dateFormat = "yyyy-mm")
'''
```


```{r}
y_var <- "Sidste måned"
order_input <- "Stigende"
niveau_in <- "Niveau 2"
year_month_input <- min(df$Dato)
```

```{r}
try <- df[df$Dato == year_month_input, ]
```


```{r}

niv_val <- list("niv_1", "niv_2", "niv_3", "niv_4")
names(niv_val) <- c("Nievau 1", "Niveau 2", "Niveau 3", "Niveau 4")
niv_in <- niv_val[[niveau_in]]

data_work <- df[!(is.na(df[[niv_in]])),]
data_work <- data_work[data_work$Dato == year_month_input,]

x_in <- data_work$beskrivelse

y_val <- list("vaerdi_i", "vaerdi_ae_m", "vaerdi_ae_aa")
names(y_val) <- c("Indeks", "Sidste måned", "Samme måned sidste år")
y_in <- y_val[[y_var]]
    
reorder_val <- list(0, -1, 1)
names(reorder_val) <- c("Numerisk", "Aftagende", "Stigende")
    
order_in <- reorder_val[[order_input]]


if(order_input == "Numerisk"){
  p <- ggplot(data=data_work, aes(x = x_in, y = .data[[y_in]])) +
    geom_bar(stat="identity") + 
    labs(x = "", y = y_var) +
    coord_flip()
} else if(order_input == "Stigende"){
  p <- ggplot(data=data_work, aes(x = reorder(x_in, .data[[y_in]]), y = .data[[y_in]])) +
    geom_bar(stat="identity") + 
    labs(x = "", y = y_var) +
    coord_flip()
} else {
  p <- ggplot(data=data_work, aes(x = reorder(x_in, desc(.data[[y_in]])), y = .data[[y_in]])) +
    geom_bar(stat="identity") + 
    labs(x = "", y = y_var) +
    coord_flip()
  
}
    
ggplotly(p)


```